[albion-online]
exe = "~/Games/albiononline/Albion-Online"

[amnesia]
exe = "~/Games/Amnesia The Dark Descent/start.sh"

[battlefront-ii]
prefix = "~/Games/star-wars-battlefront-ii"
runner = "wine"
exe = "~/Games/star-wars-battlefront-ii/drive_c/GOG Games/Star Wars - Battlefront 2/SWB2Launcher.exe"

[battlefront]
prefix = "~/Games/star-wars-battlefront"
runner = "wine"
exe = "~/Games/star-wars-battlefront/drive_c/GOG Games/Star Wars - Battlefront/LaunchBF.exe"

[caesar3]
prefix = "~/Games/caesar3"
runner = "wine"
exe = "~/Games/caesar3/drive_c/GOG Games/Caesar 3/c3.exe"
res = "1024x768"
scale = "1.40625"
winetricks = [
  "grabfullscreen=y",
  "vd=1024x768",
]

[civ3]
prefix = "~/Games/civilization3"
runner = "wine"
exe = "~/Games/civilization3/drive_c/GOG Games/Civilization III Complete/Civ3Launcher.exe"
res = "1024x768"
scale = "1.40625"
winetricks = [
  "directplay",
  "grabfullscreen=y",
  "vd=1024x768",
]

[cuphead]
prefix = "~/Games/cuphead"
runner = "wine"
exe = "~/Games/cuphead/drive_c/GOG Games/Cuphead/Cuphead.exe"

[dark-souls]
prefix = "~/Games/dark-souls"
runner = "wine"
exe = "~/Games/dark-souls/drive_c/DarkSouls/DARKSOULS.exe"
winetricks = [
  "d3dx9",
  "vd=1024x720",
  "~/.config/ley/k_lite.verb"
]

[dead-space]
prefix = "~/Games/dead-space"
runner = "wine"
exe = "~/Games/dead-space/drive_c/GOG Games/Dead Space/Dead Space.exe"

[diablo-hellfire]
dir = "~/.local/share/diasurgical/devilution/hellfire"
runner = "devilutionx"
args = ["--hellfire"]

[diablo]
dir = "~/.local/share/diasurgical/devilution"
runner = "devilutionx"

[dishonored]
prefix = "~/Games/dishonored"
runner = "wine"
exe = "~/Games/dishonored/drive_c/GOG Games/Dishonored/Binaries/Win32/Dishonored.exe"
args = ["-nostartupmovies"]

[doom2016]
prefix = "~/Games/doom-2016"
runner = "wine"
exe = "/home/zaechus/Games/doom-2016/drive_c/GOG Games/DOOM (2016)/DOOMx64vk.exe"
args = ["+com_skipIntroVideo", "1"]
winetricks = [
  "mfc140",
]

[doom2]
dir = "~/dosgames/doom2"
runner = "crispy-doom"

[doom3]
dir = "~/.local/share/dhewm3"
runner = "dhewm3"

[doom64]
prefix = "~/Games/doom-64"
runner = "wine"
exe = "~/Games/doom-64/drive_c/GOG Games/DOOM 64/DOOM64_x64.exe"
args = ["-skipmovies"]

[doom]
dir = "~/dosgames/doom"
runner = "crispy-doom"

[doomrl]
exe = "~/Games/doomrl-linux-x64-0997/doomrl"

[empire-earth]
prefix = "~/Games/empire-earth"
arch = "win32"
runner = "wine"
exe = "~/Games/empire-earth/drive_c/GOG Games/Empire Earth Gold/Empire Earth/Empire Earth.exe"
winetricks = [
  "directmusic",
  "vd=1920x1080",
]

[gog-galaxy]
# https://content-system.gog.com/open_link/download?path=/open/galaxy/client/2.0.73.27/setup_galaxy_2.0.73.27.exe
prefix = "~/Games/gog-galaxy"
wine = "wine-9.20-staging-amd64-wow64"
exe = "~/Games/gog-galaxy/drive_c/Program Files (x86)/GOG Galaxy/GalaxyClient.exe"
args = ["/runWithoutUpdating", "/deelevated"]
winetricks = [
  "corefonts",
  "mfc140",
  "win10",
]

[halo]
prefix = "~/Games/halo"
runner = "wine"
exe = "~/Games/halo/drive_c/Program Files (x86)/Microsoft Games/Halo/halo.exe"
winetricks = [
  "grabfullscreen=y",
  "mfc42",
  "winxp",
]

[heroes-of-the-storm]
env = {WINE_SIMULATE_WRITECOPY=1, STAGING_SHARED_MEMORY=1, __GL_DXVK_OPTIMIZATIONS=1, __GL_SHADER_DISK_CACHE=1}
prefix = "~/Games/heroes-of-the-storm"
wine = "wine-10.5-staging-amd64-wow64"
exe = "~/Games/heroes-of-the-storm/drive_c/Program Files (x86)/Heroes of the Storm/Heroes of the Storm.exe"
winetricks = [
  "arial",
  "d3dcompiler_43",
  "d3dcompiler_47",
  "d3dx11_42",
  "d3dx9_42",
  "dxvk_nvapi0061",
  "grabfullscreen=y",
  "ucrtbase2019",
  "vd=2560x1600",
  "vkd3d",
]

[heroes3]
prefix = "~/Games/heroes-of-might-and-magic-3-complete"
runner = "wine"
exe = "~/Games/heroes-of-might-and-magic-3-complete/drive_c/GOG Games/HoMM 3 Complete/Heroes3.exe"
res = "800x600"

[hollow-knight]
exe = "~/Games/Hollow Knight/start.sh"

[hotline-miami]
exe = "~/Games/Hotline Miami/start.sh"

[ihnm]
dir = "~/Games/i-have-no-mouth-and-i-must-scream"
runner = "scummvm"
args = ["-c", "ihnm.ini", "--themepath=scummvm"]

[jupiter-hell]
exe = "~/Games/Jupiter Hell/start.sh"

[ksp]
exe = "~/Games/kerbal-space-program/start.sh"

[lsl1]
dir = "~/Games/Leisure Suit Larry"
runner = "scummvm"
args = ["-c", "lsl1.ini", "--themepath=scummvm"]

[master]
dir = "~/dosgames/master/wads"
runner = "crispy-doom"
args = ["-iwad", "~/dosgames/doom2/DOOM2.WAD"]

[noita]
prefix = "~/Games/noita"
runner = "wine"
exe = "~/Games/noita/drive_c/GOG Games/Noita/noita.exe"

[openttd]
exe = "~/Games/OpenTTD/start.sh"

[original-war]
prefix = "~/Games/original-war"
runner = "wine"
exe = "~/Games/original-war/drive_c/GOG Games/Original War/OwarFull.exe"

[plutonia]
dir = "~/Games/final-doom/Plutonia"
runner = "crispy-doom"

[quake-enhanced]
prefix = "~/Games/quake-enhanced"
runner = "wine"
exe = "~/Games/quake-enhanced/drive_c/Quake Enhanced/Quake_Shipping_Playfab_GOG_x64.exe"
args = ["+g_showintromovie", "0"]

[quake-hipnotic]
dir = "~/dosgames/quake"
runner = "quake"
args = ["-hipnotic"]

[quake-rogue]
dir = "~/dosgames/quake"
runner = "quake"
args = ["-rogue"]

[quake]
dir = "~/dosgames/quake"
runner = "quake"

[rain-world]
prefix = "~/Games/rain-world"
runner = "wine"
exe = "~/Games/rain-world/drive_c/GOG Games/Rain World/RainWorld.exe"

[rimworld]
exe = "~/Games/rimworld/start.sh"

[silksong]
exe = "~/Games/Hollow Knight Silksong/start.sh"

[slay-the-princess]
exe = "~/Games/Slay the Princess The Pristine Cut/start.sh"

[starcraft-ii]
env = {WINE_SIMULATE_WRITECOPY=1, STAGING_SHARED_MEMORY=1}
prefix = "~/Games/starcraft-ii"
runner = "wine"
exe = "~/Games/starcraft-ii/drive_c/Program Files (x86)/StarCraft II/StarCraft II.exe"
winetricks = [
  "arial",
  "grabfullscreen=y",
  "tahoma",
  "vd=2560x1600",
]

[starcraft-remastered]
prefix = "~/Games/starcraft-remastered"
runner = "wine"
exe = "~/Games/starcraft-remastered/drive_c/Program Files (x86)/StarCraft/StarCraft Launcher.exe"
winetricks = [
  "grabfullscreen=y",
]

[starcraft]
prefix = "~/Games/starcraft"
wine = "wine-9.20-staging-amd64-wow64"
exe = "~/Games/starcraft/drive_c/Program Files (x86)/Starcraft/StarCraft.exe"
res = "640x480"
scale = "2.25"
# mouse_speed = "-0.55"
winetricks = [
  "grabfullscreen=y",
  "vd=640x480",
  "winxp",
]

[stardew-valley]
exe = "~/Games/Stardew Valley/start.sh"

[stronghold]
prefix = "~/Games/stronghold"
runner = "wine"
exe = "~/Games/stronghold/drive_c/GOG Games/Stronghold HD/Stronghold.exe"
winetricks = [
  "directplay",
  "vd=1920x1080",
]

[swat4]
prefix = "~/Games/swat4"
runner = "wine"
exe = "~/Games/swat4/drive_c/GOG Games/SWAT 4/Content/System/Swat4.exe"

[swat4x]
prefix = "~/Games/swat4"
runner = "wine"
exe = "~/Games/swat4/drive_c/GOG Games/SWAT 4/ContentExpansion/System/Swat4X.exe"

[swgb]
prefix = "~/Games/star-wars-galactic-battlegrounds"
runner = "wine"
exe = "~/Games/star-wars-galactic-battlegrounds/drive_c/GOG Games/Star Wars - Galactic Battlegrounds/swgbg.exe"
res = "1280x1024"
scale = "1.054"
winetricks = [
  "directplay",
  "grabfullscreen=y",
  "vd=1280x1024",
]

[terraria]
exe = "~/Games/Terraria/start.sh"

[tnt]
dir = "~/Games/final-doom/TNT"
runner = "crispy-doom"

[vvvvvv]
exe = "~/Games/VVVVVV/start.sh"

[wow]
prefix = "~/Games/world-of-warcraft"
runner = "wine"
exe = "~/Games/world-of-warcraft/drive_c/WoW/WoW.exe"
winetricks = [
  "grabfullscreen=y",
]

[x-wing-alliance]
prefix = "~/Games/star-wars-x-wing-alliance"
runner = "wine"
exe = "~/Games/star-wars-x-wing-alliance/drive_c/GOG Games/Star Wars - X-Wing Alliance/Alliance.EXE"
esync = false
res = "800x600"
scale = "1.8"
winetricks = [
  "directplay",
  "vd=800x600",
  "winxp",
]

[xvt]
prefix = "~/Games/sw-xvt"
runner = "wine"
exe = "~/Games/sw-xvt/drive_c/GOG Games/Star Wars - XvT/XWINGTIE.EXE"
res = "640x480"
scale = "2.25"
winetricks = [
  "directplay",
  "vd=640x480",
  "winxp",
]
